//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartoPrime.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CartoPrime.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string Locale {
            get {
                return ResourceManager.GetString("Locale", resourceCulture);
            }
        }
        
        public static string HOME_PERFIL {
            get {
                return ResourceManager.GetString("HOME_PERFIL", resourceCulture);
            }
        }
        
        public static string HOME_HISTORICO {
            get {
                return ResourceManager.GetString("HOME_HISTORICO", resourceCulture);
            }
        }
        
        public static string HOME_EDITEPERFIL {
            get {
                return ResourceManager.GetString("HOME_EDITEPERFIL", resourceCulture);
            }
        }
        
        public static string HOME_ENTREGAS {
            get {
                return ResourceManager.GetString("HOME_ENTREGAS", resourceCulture);
            }
        }
        
        public static string HOME_SAIR {
            get {
                return ResourceManager.GetString("HOME_SAIR", resourceCulture);
            }
        }
        
        public static string HOME_SAIR_DESCRICAO {
            get {
                return ResourceManager.GetString("HOME_SAIR_DESCRICAO", resourceCulture);
            }
        }
        
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        public static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        public static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        public static string HOME_PAGAMENTOS {
            get {
                return ResourceManager.GetString("HOME_PAGAMENTOS", resourceCulture);
            }
        }
    }
}
